services:
  mongo:
    image: mongo:8.0.13
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./pontos_turisticos.json:/docker-entrypoint-initdb.d/pontos_turisticos.json:ro
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
volumes:
  mongo_data: